In [6]:
import pandas as pd

In [7]:
df=pd.read_excel(r'Customer Call List.xlsx')

In [29]:
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,None,None
2,1003,Walter,/White,7066950392,298 Drugs Driveway,No,,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Yes,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,No,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,None,Shire
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Yes,,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,No,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,7066950392,3498 Super Lane,Yes,,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,No/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,None,Tatooine

In [8]:
df = df.drop(columns = "Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [30]:
df["Last_Name"] = df["Last_Name"].str.lstrip("...")
df["Last_Name"] = df["Last_Name"].str.lstrip("/")
df["Last_Name"] = df["Last_Name"].str.rstrip("_")
#df["Last_Name"] = df["Last_Name"].str.strip("123")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,False,93 West Main Street,None,None
2,1003,Walter,White,7066950392,298 Drugs Driveway,No,,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Yes,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,No,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,None,Shire
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Yes,,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,No,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,7066950392,3498 Super Lane,Yes,,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,No/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,None,Tatooine

In [31]:
df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')
df

C:\Users\Yash\AppData\Local\Temp\ipykernel_13968\430231681.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Y,False,93 West Main Street,None,None
2,1003,Walter,White,NaN,298 Drugs Driveway,No,,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,8766783469,123 Dragons Road,Yes,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,No,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,,False,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,N,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,None,Shire
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Yes,,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,No,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,NaN,3498 Super Lane,Yes,,True,3498 Super Lane,None,None
18,1019,Creed,Braton,Na,N/a,No/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,None,Tatooine

In [32]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: str(x))

df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Y,False,93 West Main Street,None,None
2,1003,Walter,White,nan--,298 Drugs Driveway,No,,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Yes,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,nan--,1209 South Street,No,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,None,Shire
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Yes,,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,No,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,nan--,3498 Super Lane,Yes,,True,3498 Super Lane,None,None
18,1019,Creed,Braton,Na--,N/a,No/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,None,Tatooine

In [33]:
df['Phone_Number']=df['Phone_Number'].str.replace('[nanNA-]','')
df

C:\Users\Yash\AppData\Local\Temp\ipykernel_13968\1111755832.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Phone_Number']=df['Phone_Number'].str.replace('[nanNA-]','')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Y,False,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,No,,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,8766783469,123 Dragons Road,Yes,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,No,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,,False,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,N,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,None,Shire
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Yes,,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,No,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,,3498 Super Lane,Yes,,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,No/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,None,Tatooine

In [34]:
df[['street_address','state','zip_code']]=df['Address'].str.split(',',2,expand=True)
df

C:\Users\Yash\AppData\Local\Temp\ipykernel_13968\1633398901.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['street_address','state','zip_code']]=df['Address'].str.split(',',2,expand=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,N,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Y,False,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,No,,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,8766783469,123 Dragons Road,Yes,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,No,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,,False,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,N,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,True,612 Shire Lane,None,Shire
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Yes,,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,No,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,N,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,,3498 Super Lane,Yes,,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,No/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,None,Tatooine

In [35]:
df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y')
df['Paying Customer']=df['Paying Customer'].str.replace('No','N')

df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Y,False,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,,False,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True,612 Shire Lane,None,Shire
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,None,Tatooine

In [22]:
df['Paying Customer']=df['Paying Customer'].str.replace('Y','Yes')
df['Paying Customer']=df['Paying Customer'].str.replace('N','No')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,93 West Main Street,None,None
2,1003,Walter,/White,7066950392,298 Drugs Driveway,No,NaN,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Yes,No,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,768 City Parkway,None,None
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,No,No,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,123 Middle Earth,None,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,612 Shire Lane,None,Shire
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Yes,NaN,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,343 City Parkway,None,None
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,No,No,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,7066950392,3498 Super Lane,Yes,NaN,True,3498 Super Lane,None,None
18,1019,Creed,Braton,N/a,N/a,No/a,Yes,True,N/a,None,None
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,910 Tatooine Road,None,Tatooine

In [36]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y')
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Y,False,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,,False,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True,612 Shire Lane,None,Shire
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,None,Tatooine

In [1]:
# Fill null values with a specific value
df['Do_Not_Contact']=df['Do_Not_Contact'].fillna('')

NameError: name 'df' is not defined

In [41]:
df.dropna()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Y,False,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,,True,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True,980 Paper Avenue,18503,Pennsylvania
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True,123 Dragons Road,None,None
5,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Y,True,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,False,1209 South Street,None,None
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Y,,False,123 Middle Earth,None,None
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True,25th Main Street,None,New York
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,True,612 Shire Lane,None,Shire
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,True,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False,2039 Main Street,None,None
13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False,343 City Parkway,None,None
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False,214 HR Avenue,None,None
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False,121 Paper Avenue,None,Pennsylvania
17,1018,Clark,Kent,,3498 Super Lane,Y,,True,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Y,True,N/a,None,None
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,None,Tatooine

In [45]:
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace=True)
        
df

,index,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,street_address,zip_code,state
0,0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,True,123 Shire Lane,None,Shire
1,1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Y,False,93 West Main Street,None,None
3,3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,True,980 Paper Avenue,18503,Pennsylvania
4,4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,True,123 Dragons Road,None,None
5,5,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Y,True,768 City Parkway,None,None
7,7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,False,98 Clue Drive,None,None
9,9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,True,25th Main Street,None,New York
12,12,1013,Don,Draper,1235432345,2039 Main Street,Y,N,False,2039 Main Street,None,None
13,13,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,False,343 City Parkway,None,None
14,14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,False,214 HR Avenue,None,None
15,15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,False,2395 Hogwarts Avenue,None,None
16,16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,False,121 Paper Avenue,None,Pennsylvania
19,19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,True,910 Tatooine Road,None,Tatooine

In [54]:
df = df.reset_index(drop=True)
df
df=df.drop(columns="index")

In [58]:

df=df.drop("Not_Useful_Column",axis=1)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street_address,zip_code,state
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,None,Shire
1,1002,Abed,Nadir,1236439775,93 West Main Street,N,Y,93 West Main Street,None,None
2,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,18503,Pennsylvania
3,1005,Jon,Snow,8766783469,123 Dragons Road,Y,N,123 Dragons Road,None,None
4,1006,Ron,Swanson,3047622467,768 City Parkway,Y,Y,768 City Parkway,None,None
5,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,N,98 Clue Drive,None,None
6,1010,Peter,Parker,1235455421,"25th Main Street, New York",Y,N,25th Main Street,None,New York
7,1013,Don,Draper,1235432345,2039 Main Street,Y,N,2039 Main Street,None,None
8,1014,Leslie,Knope,8766783469,343 City Parkway,Y,N,343 City Parkway,None,None
9,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,N,214 HR Avenue,None,None
10,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
11,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,None,Pennsylvania
12,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,None,Tatooine